-- Run this connected as the DIGIPROOF user (not SYS/SYSTEM).
-- Creates every table the FastAPI backend needs, matching api/app/models.py
-- one-for-one. Safe to re-run: it drops its own tables first if they exist.
--
-- Run as a SCRIPT (F5 in SQL Developer), not statement-by-statement,
-- because later tables have foreign keys into earlier ones.

-- ---------------------------------------------------------------- cleanup
BEGIN
    FOR t IN (
        SELECT table_name FROM user_tables
        WHERE table_name IN ('TRANSFERS', 'WARRANTIES', 'PRODUCTS', 'RETAILERS', 'USERS')
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- ---------------------------------------------------------------- users
-- One login for both retailers and customers; ROLE decides which the UI
-- treats the account as.
CREATE TABLE users (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR2(255) NOT NULL,
    password_hash  VARCHAR2(255) NOT NULL,
    full_name      VARCHAR2(120) NOT NULL,
    role           VARCHAR2(20)  NOT NULL,
    wallet_address VARCHAR2(64),
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('retailer', 'customer'))
);

-- ---------------------------------------------------------------- retailers
-- Extra business details for an account whose role is 'retailer'.
CREATE TABLE retailers (
    id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              NUMBER NOT NULL,
    business_name        VARCHAR2(160) NOT NULL,
    registration_number  VARCHAR2(80),
    created_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_retailers_user UNIQUE (user_id),
    CONSTRAINT fk_retailers_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------- products
CREATE TABLE products (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retailer_id      NUMBER NOT NULL,
    name             VARCHAR2(160) NOT NULL,
    brand            VARCHAR2(120),
    model            VARCHAR2(120),
    serial_number    VARCHAR2(120) NOT NULL,
    warranty_months  NUMBER DEFAULT 12 NOT NULL,
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_products_serial UNIQUE (serial_number),
    CONSTRAINT fk_products_retailer FOREIGN KEY (retailer_id)
        REFERENCES retailers (id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------- warranties
-- One proof of purchase per product. token_id/tx_hash/metadata_uri mirror
-- the NFT once the blockchain phase is wired up (see contracts/README.md);
-- they stay NULL until then.
CREATE TABLE warranties (
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id            NUMBER NOT NULL,
    owner_id              NUMBER NOT NULL,
    issued_by_retailer_id NUMBER NOT NULL,
    purchase_date         DATE NOT NULL,
    expires_on            DATE NOT NULL,
    price_paid            NUMBER(12, 2),
    terms                 CLOB,
    status                VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    token_id              VARCHAR2(80),
    tx_hash               VARCHAR2(80),
    metadata_uri          VARCHAR2(255),
    created_at            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_warranties_product UNIQUE (product_id),
    CONSTRAINT ck_warranties_status CHECK (status IN ('pending', 'active', 'expired', 'void')),
    CONSTRAINT fk_warranties_product FOREIGN KEY (product_id)
        REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT fk_warranties_owner FOREIGN KEY (owner_id)
        REFERENCES users (id),
    CONSTRAINT fk_warranties_retailer FOREIGN KEY (issued_by_retailer_id)
        REFERENCES retailers (id)
);

-- ---------------------------------------------------------------- transfers
-- Ownership history. Row 1 for a warranty is the mint (from_user_id NULL);
-- every resale after that adds one more row.
CREATE TABLE transfers (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warranty_id    NUMBER NOT NULL,
    from_user_id   NUMBER,
    to_user_id     NUMBER NOT NULL,
    tx_hash        VARCHAR2(80),
    transferred_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_transfers_warranty FOREIGN KEY (warranty_id)
        REFERENCES warranties (id) ON DELETE CASCADE,
    CONSTRAINT fk_transfers_from FOREIGN KEY (from_user_id)
        REFERENCES users (id),
    CONSTRAINT fk_transfers_to FOREIGN KEY (to_user_id)
        REFERENCES users (id)
);

-- ---------------------------------------------------------------- indexes
-- Primary/unique keys above already index id, email and serial_number.
-- These cover the lookups the API actually runs.
CREATE INDEX ix_products_retailer   ON products (retailer_id);
CREATE INDEX ix_warranties_owner    ON warranties (owner_id);
CREATE INDEX ix_warranties_retailer ON warranties (issued_by_retailer_id);
CREATE INDEX ix_transfers_warranty  ON transfers (warranty_id);

COMMIT;

-- Sanity check
SELECT table_name FROM user_tables ORDER BY table_name;
